version: '3'

services:
  db:
    image: neo4j
    ports:
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/s3cr3t

  book-service:
    container_name: book-service
    build:
      context: book-service
      dockerfile: Dockerfile
    image: book-service
    ports:
      - 8080:8080
    depends_on:
      - db
