version: '3'

services:
  db:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/s3cr3t

  book-service:
    hostname: book-service
    container_name: book-service
    build: .
    ports:
      - 8080:8051
    depends_on:
      - db
    environment:
      - NEO4J_HOST=db
